version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "KE:1:1,cq:1:1,cs:1:1,gs:1:1,gq:1:1,ops:1:1,announce:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      PORT_COMMAND: "docker port $$(hostname) 9092/tcp | cut -d: -f2"
      KAFKA_BROKER_ID: 123
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
